# Assumes following environment variables are set:
# AWS_ACCOUNT_ID
# CIRCLECI_JOB_AWS_ROLE (= CircleCIJobRole_$OrgId)

version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.1.2
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  deploy-aws:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - aws-cli/setup:
          role_session_name: CircleCI_Job_${CIRCLE_JOB}
          role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CIRCLECI_JOB_AWS_ROLE}
      - run:
          name: Bootstrap AWS CDK
          command: npx cdk bootstrap aws://${AWS_ACCOUNT_ID}/${AWS_DEFAULT_REGION:=us-east-1}
      - run:
          name: Deploy AWS infrastructure
          command: npx cdk deploy --require-approval never --outputs-file cdk_outputs.json
          no_output_timeout: 30m
      - run:
          name: Generate "update_kubeconfig.sh" script
          command: |
            cat cdk_outputs.json |
            jq -r '."CircleCI-EKS" | to_entries[] | select(.key|startswith("CircleCIEKSConfigCommand")).value' \
            > update_kubeconfig.sh 
            chmod +x update_kubeconfig.sh
      - persist_to_workspace:
          root: .
          paths:
            - cdk_outputs.json
            - update_kubeconfig.sh
      - kubernetes/install-kubectl
      - run:
          name: Update kubeconfig to use IAM auth
          command: ./update_kubeconfig.sh
      - run:
          name: List kubernetes system deployments
          command: kubectl get deployments -n kube-system

workflows:
  test-and-deploy:
    jobs:
      - deploy-aws