apiVersion: v1
kind: Service
metadata:
  name: helloapp
  namespace: default
  labels:
    app: helloapp
spec:
  selector:
    app: helloapp
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
