version: "3.8"
services:
  app:
    container_name: eks-devops-template
    image: eks-devops-template
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:80
