apiVersion: v1
kind: Service
metadata:
  name: helloapp
  labels:
    app: helloapp
spec:
  selector:
    app: helloapp
    tier: web
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
  labels:
    app: helloapp
spec:
  template:
    metadata:
      labels:
        app: helloapp
        tier: web
    spec:
      containers:
        - name: helloapp
          image: public.ecr.aws/nginx/nginx:1.23
          ports:
            - containerPort: 80


